repos:
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        args: []
        additional_dependencies: [
            # server packages
            fastapi==0.71.0,
            uvicorn==0.16.0,
            pydantic==1.9.0,
            python-dotenv==0.19.2,
            postgres==4.0,
            psycopg2==2.9.3,
            
            # type stubs below
            types-psycopg2==2.9.6
        ]
